### ISSUE TITLE
Unable to set table fields as editable

### ISSUE THREAD

**Issue by vishless** [arqex/react-json-table#13]
I want to make the react-json-table fields editable by the user. I've specified the return like

`return <input name="test" value={item.color} />;`

 but it doesn't seem to work. Its displaying the data in an input field but its still not editable.

You can look at the full code by following the link below.
http://codepen.io/anon/pen/ezYQZX?editors=011

**Comment by pranavek** [comment]
Change '**value**' to '**defaultValue**' 
http://codepen.io/anon/pen/yJyBvp?editors=011

Complete implementation: http://codepen.io/anon/pen/ZOEgRB?editors=011
