### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16

### ISSUE THREAD

**Issue by rickvandermey** [arqex/react-json-table#20]
https://www.npmjs.com/package/create-react-class add please :)

**Comment by vinnylinck** [comment]
In case you still need that: https://github.com/vinnylinck/react-json-table
Just point your NPM to this repo. I'm still working on fixes as they come. But don't expect many changes. Just did the minimal to get this working.

**Comment by itsdarrylnorris** [comment]
Hey @vinnylinck , 

Can you add your folk as part of a package on [NPM](https://www.npmjs.com)?

**Comment by agracio** [comment]
I also have a fork that supports React 16.x and its published to NPM. The README is not yet up to date, but feature wise it is should be backward compatible with `react-json-table` https://github.com/agracio/ts-react-json-table/

I am also working on a separate enhancements branch to add a few more features like _paging_, _global rows filter_, _column grouping_ and _'frozen' header_ that would not scroll with the rest of the table. These will take a few more weeks before they are ready though.

**Comment by itsdarrylnorris** [comment]
@agracio Great, Looking forward to the new features.
